Traceback (most recent call last):
  File "/home/ise/jsonDL/preliminary_trials/env/cnn.py", line 323, in step_in_mode_train
    tf_info, _, tf_done = next(tf_phased_train)
  File "/home/ise/jsonDL/src/train_process/tf/phased_normal.py", line 61, in phased_normal_train
    train_step(model, x, y, train_loss, train_optim, loss_metric_train, metrics_dict_train)
  File "/home/ise/jsonDL/preliminary_trials/dqn/envs/tfpMedium/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 824, in __call__
    return self._python_function(*args, **kwds)
  File "/home/ise/jsonDL/src/train_process/tf/phased_normal.py", line 96, in train_step
    predicts = model(x, training=True)
  File "/home/ise/jsonDL/preliminary_trials/dqn/envs/tfpMedium/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1012, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "/home/ise/jsonDL/preliminary_trials/dqn/envs/tfpMedium/lib/python3.7/site-packages/tensorflow/python/keras/engine/functional.py", line 425, in call
    inputs, training=training, mask=mask)
  File "/home/ise/jsonDL/preliminary_trials/dqn/envs/tfpMedium/lib/python3.7/site-packages/tensorflow/python/keras/engine/functional.py", line 560, in _run_internal_graph
    outputs = node.layer(*args, **kwargs)
  File "/home/ise/jsonDL/preliminary_trials/dqn/envs/tfpMedium/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1012, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "/home/ise/jsonDL/preliminary_trials/dqn/envs/tfpMedium/lib/python3.7/site-packages/tensorflow/python/keras/layers/convolutional.py", line 2403, in call
    data_format=self.data_format)
  File "/home/ise/jsonDL/preliminary_trials/dqn/envs/tfpMedium/lib/python3.7/site-packages/tensorflow/python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "/home/ise/jsonDL/preliminary_trials/dqn/envs/tfpMedium/lib/python3.7/site-packages/tensorflow/python/keras/backend.py", line 5538, in depthwise_conv2d
    data_format=tf_data_format)
  File "/home/ise/jsonDL/preliminary_trials/dqn/envs/tfpMedium/lib/python3.7/site-packages/tensorflow/python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "/home/ise/jsonDL/preliminary_trials/dqn/envs/tfpMedium/lib/python3.7/site-packages/tensorflow/python/ops/nn_impl.py", line 866, in depthwise_conv2d
    op=op)
  File "/home/ise/jsonDL/preliminary_trials/dqn/envs/tfpMedium/lib/python3.7/site-packages/tensorflow/python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "/home/ise/jsonDL/preliminary_trials/dqn/envs/tfpMedium/lib/python3.7/site-packages/tensorflow/python/ops/nn_ops.py", line 571, in with_space_to_batch
    return new_op(input, None)
  File "/home/ise/jsonDL/preliminary_trials/dqn/envs/tfpMedium/lib/python3.7/site-packages/tensorflow/python/ops/nn_ops.py", line 742, in __call__
    return self.call(inp, filter)
  File "/home/ise/jsonDL/preliminary_trials/dqn/envs/tfpMedium/lib/python3.7/site-packages/tensorflow/python/ops/nn_ops.py", line 561, in <lambda>
    return lambda inp, _: op(inp, num_spatial_dims, padding)
  File "/home/ise/jsonDL/preliminary_trials/dqn/envs/tfpMedium/lib/python3.7/site-packages/tensorflow/python/ops/nn_impl.py", line 858, in op
    name=name)
  File "/home/ise/jsonDL/preliminary_trials/dqn/envs/tfpMedium/lib/python3.7/site-packages/tensorflow/python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "/home/ise/jsonDL/preliminary_trials/dqn/envs/tfpMedium/lib/python3.7/site-packages/tensorflow/python/ops/nn_ops.py", line 2849, in depthwise_conv2d_native
    name=name)
  File "/home/ise/jsonDL/preliminary_trials/dqn/envs/tfpMedium/lib/python3.7/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 2195, in depthwise_conv2d_native
    _ops.raise_from_not_ok_status(e, name)
  File "/home/ise/jsonDL/preliminary_trials/dqn/envs/tfpMedium/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 6862, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: Current implementation only supports equal length strides in the row and column dimensions. [Op:DepthwiseConv2dNative]
